# custom keys

l        seek  10                       # forward 10s
h        seek -10                       # back 10s
L        seek  60                       # forward 1min
H        seek -60                       # back 1min
,        frame-back-step
.        frame-step
=        add volume  5
-        add volume -5
m        cycle mute
f        cycle fullscreen
q        quit-watch-later               # remember position
Q        quit                           # quit and forget
[        add speed -0.1
]        add speed  0.1
BS       set speed 1.0                  # backspace resets speed
